language: node_js
cache: npm
node_js:
  - 8
before_install:
  - sudo apt-get update
  - sudo apt-get install -y libudev-dev libusb-1.0-0-dev
jobs:
  include:
    - stage: Lint
      script: npm run flow:check

    - stage: Test
      script: npm run test

    - stage: Build
      script: npm run build
